# -*- coding: utf-8 -*-
"""Connect_Github from Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jI8J0nTNVnApoertziZelispCHzT7vm2
"""

!apt-get install git

!git config --global user.name "Suveetha2102"
!git config --global user.email "suveethamaheshkumar@gmail.com"

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /content/stock_data_outlier_detection
# %cd /content/stock_data_outlier_detection

!git init

!git remote add origin https://github.com/Suveetha2102/stock_data_outlier_detection.git

!mkdir stock_outlier_detection

!mv /content/your_script_name.py /content/stock_outlier_detection/